### ISSUE TITLE
Multiple channels over one connection

### ISSUE THREAD

**Issue by Daemon22** [alanxz/SimpleAmqpClient#102]
Hello,
Is there an option to open multiple channels over one connection for multi-threaded application?
I do not want to open a new connection for every thread.

Thanks.

**Comment by alanxz** [comment]
Not currently.

**Comment by kuroburki** [comment]
Alan, is there any plan to add support for #102 in near future?

**Comment by alanxz** [comment]
There are plans, but I don't have a timeline for when this will be available.

**Comment by aimdharma1990** [comment]
> There are plans, but I don't have a timeline for when this will be available.

Hi Alanxz,

Is there supported now?

**Comment by ronytigo** [comment]
AmqpClient::Channel::ptr_t connection = AmqpClient::Channel::Create("localhost");
This creates a channel or a connection?
Why there's no usage example in the docs? only this line exists in the readme.
