### ISSUE TITLE
SimpleAmqpClient.h not found

### ISSUE THREAD

**Issue by oliviermorre** [alanxz/SimpleAmqpClient#105]
Hi Alan,

I'm trying to use your library, but I'm kind of stuck right now.
A bit of context first: I'm a web developer, which mean I'm not particularly experienced in C/C++ - I struggle to remember what I'd learned in school. :-)
I'm currently working on a project where I need a C++ module to take care of large amounts of calculation - the communication between PHP and C++ will be made through RabbitMQ.

Here's what I've done:
- I installed OpenSSL. It went fine and OpenSSL 1.0.2c is now in /usr/local/lib.
- I installed rabbitmq-c (last version) and compiled it in [projectPath]/bin-rabbitmq-c (which is probably not the best choice since it's not *my* project , but whatever).
- I installed boost 1.58.0 in /usr/local/lib/boost.
- I then cloned your project to [projectPath]/, made a new dir [projectPath]/simpleamqpclient-build, moved into this new dir and ran this command:<br><br>
`cmake ../SimpleAmqpClient -DRabbitmqc_LIBRARY=[projectPath]/bin-rabbitmq-c/librabbitmq/librabbitmq.so -DRabbitmqc_INCLUDE_DIR=[projectPath]/bin-rabbitmq-c/librabbitmq -DBOOST_LIBRARYDIR=/usr/local/lib/boost/lib -DBOOST_INCLUDEDIR=/usr/local/lib/boost/include`
<br><br>and here's what I got:<br><br>
`-- The C compiler identification is GNU`<br>
`-- The CXX compiler identification is GNU`<br>
`-- Check for working C compiler: /usr/bin/gcc`<br>
`-- Check for working C compiler: /usr/bin/gcc -- works`<br>
`-- Detecting C compiler ABI info`<br>
`-- Detecting C compiler ABI info - done`<br>
`-- Check for working CXX compiler: /usr/bin/c++`<br>
`-- Check for working CXX compiler: /usr/bin/c++ -- works`<br>
`-- Detecting CXX compiler ABI info`<br>
`-- Detecting CXX compiler ABI info - done`<br>
`-- Boost version: 1.58.0`<br>
`-- Found the following Boost libraries:`<br>
`--   chrono`<br>
`--   system`<br>
`-- Found Rabbitmqc`<br>
`-- CMAKE_BUILD_TYPE not specified. Using Release build`<br>
`-- Could NOT find Doxygen  (missing:  DOXYGEN_EXECUTABLE)`<br>
`-- Configuring done`<br>
`-- Generating done`<br>
`-- Build files have been written to: [projectPath]/simpleamqpclient-build`<br><br>
Which looks fine, but SimpleAmqpClient.h is nowhere to be found.<br>

Sooo... What am I doing wrong? Is there other information I should give you?

Many thanks,
Olivier

**Comment by alanxz** [comment]
CMake doesn't actually build the project, it just generates the files that a build system uses.  Try running `cmake --build .` (or just type `make`).

**Comment by oliviermorre** [comment]
Hi, thanks for your answer !

I did what you told me but now I got this:

`Scanning dependencies of target SimpleAmqpClient`
`[ 10%] Building CXX object CMakeFiles/SimpleAmqpClient.dir/src/AmqpException.cpp.o`
`/space/www/SimpleAmqpClient/src/AmqpException.cpp:30:18: error: amqp.h: No such file or directory`
`/space/www/SimpleAmqpClient/src/AmqpException.cpp:31:26: error: amqp_framing.h: No such file or directory`
`/space/www/SimpleAmqpClient/src/AmqpException.cpp:42: error: ‘AMQP_CONTENT_TOO_LARGE’ was not declared in this scope`
`/space/www/SimpleAmqpClient/src/AmqpException.cpp:43: error: ‘AMQP_NO_ROUTE’ was not declared in this scope`
`/space/www/SimpleAmqpClient/src/AmqpException.cpp:44: error: ‘AMQP_NO_CONSUMERS’ was not declared in this scope`
`/space/www/SimpleAmqpClient/src/AmqpException.cpp:45: error: ‘AMQP_ACCESS_REFUSED’ was not declared in this scope`
`/space/www/SimpleAmqpClient/src/AmqpException.cpp:46: error: ‘AMQP_NOT_FOUND’ was not declared in this scope`
`/space/www/SimpleAmqpClient/src/AmqpException.cpp:47: error: ‘AMQP_RESOURCE_LOCKED’ was not declared in this scope`
`/space/www/SimpleAmqpClient/src/AmqpException.cpp:48: error: ‘AMQP_PRECONDITION_FAILED’ was not declared in this scope`
`/space/www/SimpleAmqpClient/src/AmqpException.cpp:49: error: ‘AMQP_CONNECTION_FORCED’ was not declared in this scope`
`/space/www/SimpleAmqpClient/src/AmqpException.cpp:50: error: ‘AMQP_INVALID_PATH’ was not declared in this scope`
`/space/www/SimpleAmqpClient/src/AmqpException.cpp:51: error: ‘AMQP_FRAME_ERROR’ was not declared in this scope`
`/space/www/SimpleAmqpClient/src/AmqpException.cpp:52: error: ‘AMQP_SYNTAX_ERROR’ was not declared in this scope`
`/space/www/SimpleAmqpClient/src/AmqpException.cpp:53: error: ‘AMQP_COMMAND_INVALID’ was not declared in this scope`
`/space/www/SimpleAmqpClient/src/AmqpException.cpp:54: error: ‘AMQP_CHANNEL_ERROR’ was not declared in this scope`
`/space/www/SimpleAmqpClient/src/AmqpException.cpp:55: error: ‘AMQP_UNEXPECTED_FRAME’ was not declared in this scope`
`/space/www/SimpleAmqpClient/src/AmqpException.cpp:56: error: ‘AMQP_RESOURCE_ERROR’ was not declared in this scope`
`/space/www/SimpleAmqpClient/src/AmqpException.cpp:57: error: ‘AMQP_NOT_ALLOWED’ was not declared in this scope`
`/space/www/SimpleAmqpClient/src/AmqpException.cpp:58: error: ‘AMQP_NOT_IMPLEMENTED’ was not declared in this scope`
`/space/www/SimpleAmqpClient/src/AmqpException.cpp:59: error: ‘AMQP_INTERNAL_ERROR’ was not declared in this scope`
`/space/www/SimpleAmqpClient/src/AmqpException.cpp:61: error: ISO C++ forbids declaration of ‘amqp_rpc_reply_t’ with no type`
`/space/www/SimpleAmqpClient/src/AmqpException.cpp:61: error: expected ‘,’ or ‘...’ before ‘&’ token`
`/space/www/SimpleAmqpClient/src/AmqpException.cpp:61: error: prototype for ‘void AmqpClient::AmqpException::Throw(int)’ does not match any in class ‘AmqpClient::AmqpException’`
`/space/www/SimpleAmqpClient/src/SimpleAmqpClient/AmqpException.h:56: error: candidates are: static void AmqpClient::AmqpException::Throw(const amqp_connection_close_t_&)`
`/space/www/SimpleAmqpClient/src/SimpleAmqpClient/AmqpException.h:55: error:                 static void AmqpClient::AmqpException::Throw(const amqp_channel_close_t_&)`
`/space/www/SimpleAmqpClient/src/SimpleAmqpClient/AmqpException.h:54: error:                 static void AmqpClient::AmqpException::Throw(const amqp_rpc_reply_t_&)`
`/space/www/SimpleAmqpClient/src/AmqpException.cpp:78: error: ISO C++ forbids declaration of ‘amqp_channel_close_t’ with no type`
`/space/www/SimpleAmqpClient/src/AmqpException.cpp:78: error: expected ‘,’ or ‘...’ before ‘&’ token`
`/space/www/SimpleAmqpClient/src/AmqpException.cpp:78: error: prototype for ‘void AmqpClient::AmqpException::Throw(int)’ does not match any in class ‘AmqpClient::AmqpException’`
`/space/www/SimpleAmqpClient/src/SimpleAmqpClient/AmqpException.h:56: error: candidates are: static void AmqpClient::AmqpException::Throw(const amqp_connection_close_t_&)`
`/space/www/SimpleAmqpClient/src/SimpleAmqpClient/AmqpException.h:55: error:                 static void AmqpClient::AmqpException::Throw(const amqp_channel_close_t_&)`
`/space/www/SimpleAmqpClient/src/SimpleAmqpClient/AmqpException.h:54: error:                 static void AmqpClient::AmqpException::Throw(const amqp_rpc_reply_t_&)`
`/space/www/SimpleAmqpClient/src/AmqpException.cpp:119: error: ISO C++ forbids declaration of ‘amqp_connection_close_t’ with no type`
`/space/www/SimpleAmqpClient/src/AmqpException.cpp:119: error: expected ‘,’ or ‘...’ before ‘&’ token`
`/space/www/SimpleAmqpClient/src/AmqpException.cpp:119: error: prototype for ‘void AmqpClient::AmqpException::Throw(int)’ does not match any in class ‘AmqpClient::AmqpException’`
`/space/www/SimpleAmqpClient/src/SimpleAmqpClient/AmqpException.h:56: error: candidates are: static void AmqpClient::AmqpException::Throw(const amqp_connection_close_t_&)`
`/space/www/SimpleAmqpClient/src/SimpleAmqpClient/AmqpException.h:55: error:                 static void AmqpClient::AmqpException::Throw(const amqp_channel_close_t_&)`
`/space/www/SimpleAmqpClient/src/SimpleAmqpClient/AmqpException.h:54: error:                 static void AmqpClient::AmqpException::Throw(const amqp_rpc_reply_t_&)`
`make[2]: *** [CMakeFiles/SimpleAmqpClient.dir/src/AmqpException.cpp.o] Error 1`
`make[1]: *** [CMakeFiles/SimpleAmqpClient.dir/all] Error 2`
`make: *** [all] Error 2`

I'm not worried about the SOME_CONSTANT not being defined, as I suppose it will be resolved as soon as the first errors are fixed, but I don't understand the first tow errors, about amqp.h and amqp_framing.h not being foud. I passed the paths when I called the first cmake (see my first message). Besides, (again, I'm not a C++ developper, but) I don't get why AmqpException.cpp tries to include <amqp.h> and <>

**Comment by alanxz** [comment]
Look at the first error. You have not correctly specified the directory that rabbitmq-c is installed in to CMake.

Make sure `Rabbitmqc_INCLUDE_DIR` is set to the directory that the rabbitmq-c header files are installed in.
