### ISSUE TITLE
VS2015 and SimpleAmqpClient

### ISSUE THREAD

**Issue by kreuzerkrieg** [alanxz/SimpleAmqpClient#109]
Just upgraded our solutions to VS2015. I've built the latest client, with latest rabbitmq-c (static) and latest openssl (static). Everything looks fine except one issue - the client doesnt work. It fails in channels DoLogin with AMQP_RESPONSE_LIBRARY_EXCEPTION. Please advise.

Let me know if any additional information needed.

**Comment by kreuzerkrieg** [comment]
ok, looks like the rabbitmq-c is one to blame. dropped back to 0.5.2 and everything works. the 0.7 behaves as above and the RabbitMQ server log reports:
=INFO REPORT==== 24-Aug-2015::11:00:02 ===
accepting AMQP connection <0.338.0> (1.1.1.1:48057 -> 2.2.2.2:5672)

=WARNING REPORT==== 24-Aug-2015::11:00:05 ===
closing AMQP connection <0.338.0> (1.1.1.1:48057 -> 2.2.2.2:5672):
connection_closed_abruptly

**Comment by alanxz** [comment]
What version of windows is this running on?

**Comment by kreuzerkrieg** [comment]
clinents: Win7x64/Win2k8R2x64
Rabbit: Win2k8R2x64/CentOs

**Comment by AnthonyMullerPlayground** [comment]
same issue :(

**Comment by alanxz** [comment]
There was a bug in rabbitmq-c v0.7.0 that affected Win32 users. Try using rabbitm-c v0.7.1 which should address this issue.

**Comment by alanxz** [comment]
Given no further reports, I'm assuming this was an issue with rabbitmq-c and not SimpleAmqpClient. Closing.
