### ISSUE TITLE
error LNK2019 when linking SimpleAmqpClient on new VS projects

### ISSUE THREAD

**Issue by rabellogp** [alanxz/SimpleAmqpClient#112]
I'm getting LNK2019 errors when I try to build a project that includes and uses SimpleAmqpClient lib.

I can successfully build all the required libraries on both Win32 and x64 versions. When I try to include SimpleAmqpClient on a new project (a simple Win32 Console application) with the *simple_connect.cpp* example code. VC asks for *SimpleAmqpClient.h* location before I set the proper folders on VC++ Directories (as expected). After that, it will asks for *boost/cstdint.hpp* wich is also solved after proper setting *boost lib root folder* on VC++ Directories. With both links configured, I'll get the following errors that I can't figure out how to solve:
```c++
1>ConsoleApplication3.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: static class boost::shared_ptr<class AmqpClient::BasicMessage> __cdecl     AmqpClient::BasicMessage::Create(void)" (__imp_?Create@BasicMessage@AmqpClient@@SA?AV?$shared_ptr@VBasicMessage@AmqpClient@@@boost@@XZ) referenced in function wmain
1>ConsoleApplication3.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl AmqpClient::BasicMessage::Body(void)const " (__imp_?Body@BasicMessage@AmqpClient@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ) referenced in function wmain
1>ConsoleApplication3.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: void __cdecl AmqpClient::BasicMessage::Body(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (__imp_?Body@BasicMessage@AmqpClient@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) referenced in function wmain
1>ConsoleApplication3.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class boost::shared_ptr<class AmqpClient::BasicMessage> __cdecl AmqpClient::Envelope::Message(void)const " (__imp_?Message@Envelope@AmqpClient@@QEBA?AV?$shared_ptr@VBasicMessage@AmqpClient@@@boost@@XZ) referenced in function wmain
1>ConsoleApplication3.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: static class boost::shared_ptr<class AmqpClient::Channel> __cdecl AmqpClient::Channel::Create(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int)" (__imp_?Create@Channel@AmqpClient@@SA?AV?$shared_ptr@VChannel@AmqpClient@@@boost@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H000H@Z) referenced in function wmain
1>ConsoleApplication3.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl AmqpClient::Channel::DeclareQueue(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,bool,bool,bool,bool)" (__imp_?DeclareQueue@Channel@AmqpClient@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV34@_N111@Z) referenced in function wmain
1>ConsoleApplication3.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: void __cdecl AmqpClient::Channel::BindQueue(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (__imp_?BindQueue@Channel@AmqpClient@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@00@Z) referenced in function wmain
1>ConsoleApplication3.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: void __cdecl AmqpClient::Channel::BasicPublish(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class boost::shared_ptr<class AmqpClient::BasicMessage>,bool,bool)" (__imp_?BasicPublish@Channel@AmqpClient@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0V?$shared_ptr@VBasicMessage@AmqpClient@@@boost@@_N2@Z) referenced in function wmain
1>ConsoleApplication3.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl AmqpClient::Channel::BasicConsume(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,bool,bool,bool,unsigned short)" (__imp_?BasicConsume@Channel@AmqpClient@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV34@0_N11G@Z) referenced in function wmain
1>ConsoleApplication3.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class boost::shared_ptr<class AmqpClient::Envelope> __cdecl AmqpClient::Channel::BasicConsumeMessage(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (__imp_?BasicConsumeMessage@Channel@AmqpClient@@QEAA?AV?$shared_ptr@VEnvelope@AmqpClient@@@boost@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) referenced in function wmain
1>d:\documents\visual studio 2013\Projects\ConsoleApplication3\x64\Debug\ConsoleApplication3.exe : fatal error LNK1120: 10 unresolved externals
```

I've search pretty much everything I could find on how to proper build **boost lib**, **rabbitmqc**, **SimpleAmqpClient** and how to proper link them. I've also tried both x64 and x86 versions (building every lib with the proper architecture). Some info of everything that I've already tried:

* **Systems where I've tested:** Windows 8.1 and Windows 10, Visual Studio 12 (2013), cmake **2.8.12.2** and **3.3.2** - I'm using the GUI tool
* **Boost:** I've tried **1.58** and **1.59** versions, both for x86 and x64 platforms. Always setting the *BOOST_ROOT* system var to the boost root so Cmake can find it by itself.
* **rabbitmqc:** I've tried both "master" and "0.7.0 (last stable)" versions. I don't need SSL, but I've also tried to build a version with that feature turned on(wich requires OpenSSL lib) just in case SimpleAmqpClient still requires rabbitmqc with SSL...
* **SimpleAmqpClient**: I've tried it with static and dynamic Boost libs.
* **Cmake:** I'm using the GUI tool only. I started with the last version (3.3.2), but also tried the 2.8 wich is the earlier supported version listed on the SimpleAmqpClient readme. On *Rabbitmqc_INCLUDE_DIR I'm setting* **rabbitmq-c-master/librabbitmq** folder and on *Rabbitmqc_LIBRARY* I'm setting **rabbitmq.4.lib**

I'm always double checking the *project properties* on VC to make sure all the libraries and includes directories are properly pointed (under VC++ Directories). And I'm also making sure to set Win32 or x64 properly on my test project depending on wich version of the libraries I'm using...

Am I missing something here? After almost two weeks of looking into it I'm pretty much out of ideas... 

Ps: Sorry for my poor English

**Comment by alanxz** [comment]
When compiling your application make sure you link against the SimpleAmqpClient library.

**Comment by rabellogp** [comment]
Found the issue. I wasn't linking SimpleAmqpClient.lib and rabbitmq.lib properly indeed. The right way to do it is manually adding SimpleAmqpClient.2.lib and rabbitmq.4.lib on Properties > Linker > Imput > Aditional Dependencies.

**Comment by ngoctrungpro** [comment]
> Found the issue. I wasn't linking SimpleAmqpClient.lib and rabbitmq.lib properly indeed. The right way to do it is manually adding SimpleAmqpClient.2.lib and rabbitmq.4.lib on Properties > Linker > Imput > Aditional Dependencies.

Hi rabellogp

I am having the same problem as you.

Could you please send me the library SimpleAmqpClient.2.lib and rabbitmq.4.lib?
Or maybe you send me a small project on how to use the SimpleAmqpClient library?

Sincerely thank,
