### ISSUE TITLE
Channel::Channel(...) does not support a timeout parameter ?

### ISSUE THREAD

**Issue by panxianzhan** [alanxz/SimpleAmqpClient#114]
Hi. It's really nice to have this client. 

I have been using this library in my single-threaded program recently. The IP parameter of  Channel::Channel(...) is read in a config. If it' an invalid IP, the program  keep blocking with no runtime errors no exception.

May I have any methods to test the ip parameter without modifying the lib's code?

**Comment by alanxz** [comment]
SimpleAmqpClient does not provide a non-blocking call to connect to a host.

**Comment by panxianzhan** [comment]
thanks for help.
