### ISSUE TITLE
CRT problems

### ISSUE THREAD

**Issue by leogi22** [alanxz/SimpleAmqpClient#117]
I am having trouble solving some CRT problems between my exe and the simpleamqpclient2.lib and boost 1.59 and the rabbitmq.4.lib

I've used cmake/VS 2013 to build to rabbitmq.4.lib, using /MTd and producing a .lib

I then used cmake with the Boost_USE_STATIC_LIBS=ON flag (in cmake gui by adding Entry), then built the simpleamqpclient2.lib by linking against the boost

libboost_chrono-vc120-mt-sgd-1_59.lib and
libboost_system-vc120-mt-sgd-1_59.lib
rabbitmq.4.lib, using the /MTd CRT setting as well

It built fine.

I then linked my exe to the libs
My exe uses the /MTd CRT setting.
I then load the the simpleamqpclient.h and run the exe

1 - AmqpClient::Channel::ptr_t channel = AmqpClient::Channel::Create("localhost");
2 - std::string myqueue("my_queue");
3 - myqueue = channel->DeclareQueue(std::string(""), false, false, false, true);

Every time I get the following error:

dbgheap.c line 1424
Expression pFirstBlock == phead

whenever line 2 is executed and the string is being deleted

which suggests a problem between the heaps. Based on what I could find, it has to do with the exe and the dll using different version of the CRT, which is not the case since everything is compiled using the /MTd option, and the libboost libraries are using statically. I did try different combinations of /MTd and /MDd.
Please help!
Also, I'm new to the cmake utility, It appears that the solution it builds for the simpleamqpclient produces both a simpleamqpclient.lib and a simpleamqpclient.dll, and then I link in the exe to the simpleamqpclient2.lib. Is that correct?

**Comment by alanxz** [comment]
You've probably compiled one part against the debug version of the CRT and one part of your application against the non-debug version of the CRT. Make sure all components of the library are compiled with the same version of the CRT.
