### ISSUE TITLE
why is it  more slowly than python lib pika

### ISSUE THREAD

**Issue by week008** [alanxz/SimpleAmqpClient#118]
when I used the SimpleAmqpClient lib to test publish message, it is about 1000 msg/s, it's two slowly; But I used the python lib pika to test, it is about 6000 msg/s.  I used the same RabbitMQ server. That's why? 

    Channel::ptr_t channel = Channel::Create("10.2.1.90", 5672, "test", "123456", "/", 40096);
    std::string exchange_name = "pub1exchange";                                                                                         
    channel->DeclareExchange(exchange_name, "fanout", false, false, false);
    for(int i=0; i<1000000; i++)
    {   
        channel->BasicPublish(exchange_name, "", BasicMessage::Create("hello fanout")); 
    }

**Comment by alanxz** [comment]
SimpleAmqpClient waits for an publisher confirm from the broker on each message that is published, which effectively makes publishing a message a synchronous operation. (This is a design decision baked into SimpleAmqpClient that won't change). Without looking at your publish code in Pika, I suspect it doesn't wait for an acknowledgement from the broker on each publish, thus it will have a better throughput.

**Comment by week008** [comment]
This is python code with Pika lib. It used confimation mechanism. It is about 6000 msg/s. 

#!/usr/bin/python
import pika
credentials = pika.PlainCredentials('test', '123456')
connection = pika.BlockingConnection(pika.ConnectionParameters('10.2.1.90', 5672, '/', credentials))
channel = connection.channel()
channel.exchange_declare(exchange='pub1exchange', type="fanout", durable=False)
channel.confirm_delivery()
for i in range(100000): 
    channel.basic_publish(exchange='pub1exchange', routing_key='', body='hello world '+ str(i))                                         
    print "Sent 'hello world %d" % (i) 
connection.close()

**Comment by alanxz** [comment]
As far as I can tell the python code does not wait for a basic.ack from the broker before publishing the next message.

**Comment by week008** [comment]
thank your fro your answer, alanxz
