### ISSUE TITLE
Incorrect host exception

### ISSUE THREAD

**Issue by kargapoltsev** [alanxz/SimpleAmqpClient#119]
How to catch error of incorrect host (without RabbitMQ or it down)?

The code 
```
AmqpClient::Channel::ptr_t connection = AmqpClient::Channel::Create("localhost");
```
just freezes in my app.

**Comment by alanxz** [comment]
It's blocked on the socket timing out in connecting to localhost.  You need to catch a `AmqpLibraryException`

**Comment by kargapoltsev** [comment]
But if i want to connect to not only localhost?

**Comment by alanxz** [comment]
Instead of "localhost" for the first parameter for AmqpClient::Channel::Create, use the hostname of the broker you want to connect to.
