### ISSUE TITLE
No queue exception in consumer once it is restared

### ISSUE THREAD

**Issue by mowaiskhan** [alanxz/SimpleAmqpClient#128]
Hello,

I split the code of simple_connect.cpp into sender.cpp and receiver.cpp as below.

Problem is this that when I re-start receiver, it throws below exception even though the sender.exe is running.

[iris@OwaisCentOS7 examples]$ ./receive.exe
terminate called after throwing an instance of 'AmqpClient::NotFoundException'
  what():  channel error: 404: AMQP_BASIC_CONSUME_METHOD caused: NOT_FOUND - no queue 'alanqueue' in vhost '/'
Aborted (core dumped)

I will appreciate any help on this.

Thanks & Regards,
Owais.

**sender.cpp**

```
#include <SimpleAmqpClient/SimpleAmqpClient.h>
#include <iostream>
#include <stdlib.h>
using namespace std;
using namespace AmqpClient;
int main()
{
    char *szBroker = getenv("AMQP_BROKER");
    Channel::ptr_t channel;
    if (szBroker != NULL)
        channel = Channel::Create(szBroker);
    else
        channel = Channel::Create();

    channel->DeclareQueue("alanqueue", false,false,false,true);
    channel->BindQueue("alanqueue", "amq.direct", "alankey");

    BasicMessage::ptr_t msg_in = BasicMessage::Create();

    for (int i = 0;i < 10000; i++)
    {
        string message;
        if( i%2 == 0)
        {
            message = "Message-1";
            msg_in->Body(message);
            channel->BasicPublish("amq.direct", "alankey", msg_in);
        }
        else
        {
            message = "Message-2";
            msg_in->Body(message);
            channel->BasicPublish("amq.direct", "alankey", msg_in);
        }
        sleep(10);
    }
    return 0;
}
```

**receiver.cpp**

```
#include <SimpleAmqpClient/SimpleAmqpClient.h>
#include <iostream>
#include <stdlib.h>

using namespace AmqpClient;
using namespace std;
int main()
{
    char *szBroker = getenv("AMQP_BROKER");
    Channel::ptr_t channel;
    if (szBroker != NULL)
        channel = Channel::Create(szBroker);
    else
        channel = Channel::Create();

    channel->BasicConsume("alanqueue", "consumertag");

    while(1)
    {
    BasicMessage::ptr_t msg_out = channel->BasicConsumeMessage("consumertag")->Message();
    std::cout << "Message text: " << msg_out->Body() << std::endl;
    }
}
```

**Comment by alanxz** [comment]
The failure you're getting is because `alanqueue` is declared auto-delete, which means its automatically deleted by the broker when the last consumer disconnects.  Either do not set `auto-delete` when declaring the queue or have the receiver declare and bind the queue when it starts up (depending on what behavior you want when the receiver isn't actively handling messages).

FYI: these sorts of questions are better asked on the [simpleamqpclient-users](https://groups.google.com/forum/#!forum/simpleamqpclient-users) or on [Stackoverflow](http://stackoverflow.com/).

**Comment by swatinair123** [comment]
@mowaiskhan Hi is the above issue solved ? I am getting AmqpClient::AccessRefusedException at memory location 0x008FF080 at channel->BindQueue(queue, exchange, routing_key); . I am running the code in x32 and Debug mode.

**Comment by swatinair123** [comment]
Can you pls suggest any suitable fix?
