### ISSUE TITLE
Unexpected exception when connecting by user guest to remote host

### ISSUE THREAD

**Issue by EvilBeaver** [alanxz/SimpleAmqpClient#129]
guest user can connect only to a localhost, it's ok. But when your customer anyway tries to do this, SimpleAmqpClient throws **logic_error** instead of **AccessRefusedException**

Reason:
```
void AmqpException::Throw(const amqp_connection_close_t &reply)

// bla-bla

    case InternalErrorException::REPLY_CODE:
        throw InternalErrorException(what.str(), reply_text, reply.class_id, reply.method_id);
    default:
		throw std::logic_error(std::string("Programming error: unknown connection reply code: ").append(boost::lexical_cast<std::string>(reply.reply_code))

```

switch above doesn't handle response code 403. It handled only for "channel exception", but error 403 happens also as "connection exception".

**Comment by alanxz** [comment]
Fixed in master. Thanks for reporting this.
