### ISSUE TITLE
'boost::make_shared' : not a function

### ISSUE THREAD

**Issue by kmgalanakis** [alanxz/SimpleAmqpClient#130]
Hi!

When running your examples, I always get errors like the following: 

> error C2063: 'boost::make_shared' : not a function	c:\vs2013 projects\rabbitmqtutorialv2\rabbitmqtutorialv2\simplesubscriber.h	54	1	RabbitMQTutorialV2

on lines like the following

```
friend ptr_t boost::make_shared<SimpleSubscriber>(AmqpClient::Channel::ptr_t const &a1, std::string const &a2);
```

Can you help me please?

**Comment by alanxz** [comment]
The examples were written for an earlier version of the library. They do not work with the current version of the library, though they can be used as a starting point.
