### ISSUE TITLE
msvc14.0 x64 build - Unresolved external symbols EXCHANGE_TYPE_DIRECT, EXCHANGE_TYPE_FANOUT, EXCHANGE_TYPE_TOPIC

### ISSUE THREAD

**Issue by kuroburki** [alanxz/SimpleAmqpClient#132]
As stated in title, my client program compiled in VS2015 (msvc14.0 x64) runs to linker error when I use string constants from Channel interface. I have built both rabbitmq-c and SimpleAmqpClient libraries in shared format (dll).

**Comment by alanxz** [comment]
How are you compiling SimpleAmqpClient?

Those symbols should be correctly dllexported.  This leads me to believe they're not being correctly exported from the library.

**Comment by kuroburki** [comment]
Alan, I have an update on this. My client program, a msvc14 Console application, did not explicitly define WIN32 (/DWIN32) as a compiler option. I am looking up if this is meant to be implicitly defined by the IDE/Build or if I should set the flag myself in the project.

**Comment by kuroburki** [comment]
Setting WIN32 explicitly fixed this issue.
