### ISSUE TITLE
SimpleAmqpClient Rabbitmq tutorial

### ISSUE THREAD

**Issue by vvritul** [alanxz/SimpleAmqpClient#133]
Hello, I want to use SimpleAmqpClient for RabbitMQ.
I want to publish messages from C++ and catch them in Java Spring App.
I have already built it, but unfortunately there is no examples how to use it.

Do you have some sort of tutorial like https://www.rabbitmq.com/tutorials/tutorial-one-java.html here ?

Thank you for your help.
B/R Sergey

**Comment by alanxz** [comment]
Not currently.
