### ISSUE TITLE
Is there a way to create multiple channels for single connection?

### ISSUE THREAD

**Issue by nishantd01** [alanxz/SimpleAmqpClient#134]
Currently `Channel::Create();` creates a single channel on a connection. 

Is there a way we can multiplex multiple channels using a single TCP connection to the broker?

**Comment by alanxz** [comment]
The `Channel` class is a poorly named. A SimpleAmqpClient Channel object is logically an AMQP Connection.  Internally it maintains a pool of AMQP Channels, it tries to be intelligent about how it uses AMQP Channels (it uses them as error-domains), and thus provides no user-visible way to control this.
