### ISSUE TITLE
AmqpLibraryException issue

### ISSUE THREAD

**Issue by gizfernz** [alanxz/SimpleAmqpClient#135]
Hi,

I have used BasicConsumeMessage()  in an infinite while loop using a timeout of 10milliseconds. Sometimes it returns a AmqpLibraryException. After this exception I am unable to consume anymore messages and it always returns the exception. How do I disconnect from this connection and reconnect? i use the following code

Channel::ptr_t channel = Channel::Create(ipadress,port,username,password,"/");
if the  above connection channel is not null, I declare the exchange name and queue name and bind to the queue

channel->DeclareExchange(exchangename,"fanout");
channelqueue= channel->declarequeue(queuename,false,false,false,false);
channel->BindQueue(channelqueue,exhangename,"");
channelconsumetag= channel->BasicConsume(channelqueue,"consumer");

while(1)
{
try
{
Envelope::ptr_t msg;
bool consume = false
consume = channel->BasicConsumeMessage(channelconsumetag,msg,timeout);
if(consume)
{
//treat the message
}
}
catch()
{
}
}

How do I close the connection and reconnect?

**Comment by alanxz** [comment]
Deleting the Channel object will close the connection.  Create a new channel object to close the channel.

**Comment by lqj1990** [comment]
How to delete a Channel object? 
Can I use channel_ptr_t->~Channel() to delete a channel object? 
If a channel object is deleted, the auto-deleted exchange and queue in that channel will be deleted. Is it right?

**Comment by alanxz** [comment]
> How to delete a Channel object?
> Can I use channel_ptr_t->~Channel() to delete a channel object?
Yes the destructor on the Channel::ptr_t object will close the underlying connection to the broker.

> If a channel object is deleted, the auto-deleted exchange and queue in that channel will be deleted. Is it right?

Any auto-delete exchange or queues will also be deleted on the broker when the channel is destroyed and the underlying connection terminated.
