### ISSUE TITLE
How to build static library libSimpleAmqpClient.a

### ISSUE THREAD

**Issue by dixudx** [alanxz/SimpleAmqpClient#137]
I need to use static library `libSimpleAmqpClient.a` when linking with my program.

So I wanna how to build this `libSimpleAmqpClient.a`. I've tried several ways, but no results.

**Comment by alanxz** [comment]
Use `-DBUILD_SHARED_LIBRARY=FALSE` when running cmake.

**Comment by dixudx** [comment]
Should be `-DBUILD_SHARED_LIBS=FALSE`.

@alanxz Thanks so much for your help.
