### ISSUE TITLE
Error -> Create connection

### ISSUE THREAD

**Issue by RMaster15** [alanxz/SimpleAmqpClient#139]
hi :) i will try this library but i have the follow error:

"obj/Debug/main.o: In function `boost::detail::sp_if_not_array<AmqpClient::Channel>::type boost::make_shared<AmqpClient::Channel, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int&>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int&)':"

My main class only have this line (as in the example)

AmqpClient::Channel::ptr_t connection = AmqpClient::Channel::Create("localhost");

I dont understand the error. This error appear when i try to build the code in codeblocks. I have the SimplesAmqpClient.h include and not appear any error before i build the code. 
Thanks. I expected an answer! ;)

**Comment by alanxz** [comment]
Please ask this question on [simpleamqpclient-users](https://groups.google.com/forum/#!forum/simpleamqpclient-users).
