### ISSUE TITLE
NuGet Visual Studio 2015 support

### ISSUE THREAD

**Issue by damian123** [alanxz/SimpleAmqpClient#140]
Are there any plans to add support for VS 2015?

**Comment by alanxz** [comment]
What's involved in supporting NuGet?

I generally don't include distro specific packaging as a part of the library (there's just too many different distributions and ways of packaging across different platforms). If someone else wants to maintain the necessary configs for this, I can provide pointers if they get stuck.

**Comment by damian123** [comment]
Thank you for clarifying.

I can see Santos created the current package: https://www.nuget.org/profiles/lsantos

**Comment by alanxz** [comment]
Sounds good.
