### ISSUE TITLE
Exception when using "Channel::ptr_t channel = Channel::Create()"

### ISSUE THREAD

**Issue by lqj1990** [alanxz/SimpleAmqpClient#142]
I am new to using rabbitmq and the C++ wrapper SimpleAmqpClient. But when I try to write some code to, I failed at the first step. My code is
`const char *host = getenv("AMQP_BROKER");`
`string addr = "";`
`if (NULL != host) {
         addr = std::string(host);
}`
`Channel::ptr_t channel = Channel::Create(addr, 5672, "guest", "guest", "/", 400);
`
And it will cause AmqpClient::AmqpLibraryException. 
When I debug the code, I find that all the string data (such as host, username, password, vhost) can't input properly, it warns that "Invalid characters in a string" or "Error while reading the character of the string". I doubt whether the improper value causes the exception. Even I just use Channel::Create(), the problem still exist.
How to solve it? Can anyone help me? Thank you very much!

Also, I don't know why  `getenv("AMQP_BROKER")` used in the example code. It seems that "AMQP_BROKER" is an environment variable, but I don't know what value it should be set. In fact, in my code, the output of host is null.

**Comment by alanxz** [comment]
The first parameter of [Create::Create](https://github.com/alanxz/SimpleAmqpClient/blob/5bc25213018add1939231352b759c828f295c812/src/SimpleAmqpClient/Channel.h#L67) is the broker hostname, e.g., `"localhost"` if the broker happens to be running on the same machine as your client.

The `AMQP_BROKER` environment variable is only used by the tests, you do not need to use this to use the library. 

FYI: these sorts of questions are better asked on the [simpleamqpclient-users](https://groups.google.com/forum/#!forum/simpleamqpclient-users) or on [Stackoverflow](http://stackoverflow.com/).

**Comment by swatinair123** [comment]
Hi i am not able to access ptr_t using Channel::ptr_t .It says no member ptr_t. Please tell me what could be the possible issue
