### ISSUE TITLE
Crash on TableValueImpl::CopyTableInner

### ISSUE THREAD

**Issue by leleftheriades** [alanxz/SimpleAmqpClient#148]
I use v0.8.0 (downloaded on aug 2016) of rabbitmq-c and got a crash.

I am pasting the call stack below

```
165c60 _amqp_decode_method
55c60 struct amqp_table_t_ AmqpClient::Detail::TableValueImpl::CopyTableInner(struct amqp_table_t_ const &,struct amqp_pool_t_ &)
54a0 class std::_Tree_iterator<class std::_Tree_val<struct std::_Tree_simple_types<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class AmqpClient::TableValue> > > > std::_Tree<class std::_Tmap_traits<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class AmqpClient::TableValue,struct std::less<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,class std::allocator<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class AmqpClient::TableValue> >,0> >::erase(class std::_Tree_const_iterator<class std::_Tree_val<struct std::_Tree_simple_types<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class AmqpClient::TableValue> > > >)
```

**Comment by alanxz** [comment]
What version of SimpleAmqpClient were you using?

Do you have a minimal example that demonstrates the crash?

**Comment by leleftheriades** [comment]
v2,5.0 pulled from master branch on  23/1/2017

I cannot reproduce the crash as i don't know under what conditions it occurred and it happened only once in a month of heavy usage.

**Comment by alanxz** [comment]
Looking at the stacktrace a bit, it doesn't seem to make a whole lot of sense (are there some frames missing?, `TableValueImpl::CopyTable` doesn't deal with any STL datastructures; the call to what looks like `map::erase` doesn't make sense there).

When you say crash, what sort of crash are you talking about? A SEGFAULT, something else?

**Comment by leleftheriades** [comment]
I don't know the type of crash. The program that uses the rabbitmq library is a dll that is loaded by a software that has debugger protection. When it crashes it just spits out the stack trace output. It did come with the following warning though before listing the call stack:

WARNING: Stack unwind information not available. Following frames may be wrong.

**Comment by alanxz** [comment]
Given the stack-trace is likely incorrect, and there isn't any additional information about what failed. Its hard to diagnose whats going on.

I'll leave this open, but I cannot help further without more information or some way to reproduce the failure.

**Comment by leleftheriades** [comment]
Close it and i will compile with /Oy- so that I can get an accurate stack-trace and if it is related to rabbitmq i will reopen. Thank u :)
