### ISSUE TITLE
 BasicConsumeMessage hang 10sec

### ISSUE THREAD

**Issue by haolujun** [alanxz/SimpleAmqpClient#150]
HI alanxz:
    when I used the function BasicConsumeMessage  to get message from mq, I found it sometimes hanged 10sec, so in this 10sec couldn't get anything。I made 8 consumers for a queue，each consumer in a single thread，and each thread used the different channel which made by itself。 The Version I used was SimpleAmqpClient-2.4.0。Looking forward to your reply，thank you！

**Comment by haolujun** [comment]
May be I made a mistake, Not the conumser hang 10sec, the truth is that producer hang 10sec, producer couldn't push message to the queue in these 10 secs, so as the consumer got nothing.

**Comment by haolujun** [comment]
HI alanxz:
      I trace the stack when producer hanged 10sec, and stack is below:
![stack](https://cloud.githubusercontent.com/assets/10751631/23350937/f7013bac-fcf8-11e6-9fcb-5f8813226682.png)
，It may be something happend in rabbimtmq-c。

**Comment by haolujun** [comment]
HI alanxz:
I think I found that：message_ptr->DeliveryMode(AmqpClient::BasicMessage::dm_persistent) made producer hang 10sec。But I don't know why? When I use the python client and set message deliver mode is 2, it won't be hanged. It's so amazing!!

**Comment by alanxz** [comment]
In SimpleAmqpClient `BasicPublish` waits for the broker to return a publisher confirmation before returning, the dm_persistent causes the broker to sync the message to persistent storage, which can be slow. (the python client doesn't wait for the confirmation, I believe it allows registration of a callback that is called when a confirmation is received).

This is a design decision for how SimpleAmqpClient works, which makes its somewhat slow at publishing messages.

If you don't need message persistence, I'd recommend turning that off.

**Comment by haolujun** [comment]
Thanks for your reply. I will turn it off。
