### ISSUE TITLE
Channel as class member

### ISSUE THREAD

**Issue by enochtsang** [alanxz/SimpleAmqpClient#156]
I'm facing a seg fault when assigning a connection to a class member.

```
#pragma once

#include <SimpleAmqpClient/SimpleAmqpClient.h>

class Foo
{
public:
    Foo();
    bool attemptConnection();

private:
    AmqpClient::Channel::ptr_t channel_;
};
```

```
#include "Foo.h"

Foo::Foo()
{
}

bool Foo::attemptConnection()
{

    try
    {
        // Line below doesn't seg fault
        AmqpClient::Channel::ptr_t channel = AmqpClient::Channel::Create();
        // Line below seg faults
        channel_ = channel;
    }
    catch (AmqpClient::AmqpException::exception&)
    {
        return false;
    }
    return true;
}
```

When running attemptConnection, GDB gives:
```
Thread 1 "Test" received signal SIGSEGV, Segmentation fault.
0x00000000004189af in std::swap<AmqpClient::Channel*> (__a=@0x7fffffffcda0: 0x8bfd10, 
    __b=@0x86: <error reading variable>) at /usr/include/c++/5/bits/move.h:186
186	      __a = _GLIBCXX_MOVE(__b);
```

How can I assign this member?

**Comment by alanxz** [comment]
For whatever reason it looks like the computer is trying to do a std::move operation on a boost::shared_ptr and failing. Its unclear to me why that should fail.

Do you get the same problem when you assign it directly to the member? E.g.,

```
channel_ = AmqpClient::Channel::Create();
```

What platform, compiler, and version of boost are you using?

**Comment by enochtsang** [comment]
Linux Mint Xenial, boost 1.58, 5.3.1

Yes assigning directly to the member gives the same seg fault. If I call `Create()` in constructor it does not seg fault either.

**Comment by enochtsang** [comment]
It was an external issue, no issue with the library.
