### ISSUE TITLE
How to set timeout for publishing a message?

### ISSUE THREAD

**Issue by lqj1990** [alanxz/SimpleAmqpClient#158]
Here is my scenario, when I publish a message, I don't care if it has been published successfully. 

If I lose connection before publishing a message, the BasicPublish function will hang until it detects the problem then it will throw an exception. It usually will take several seconds which will block a thread.

Is there any way to set a timeout for publishing a message, so the thread will not be blocked too long. Or is there any other way to deal with the connection problem during publishing process?

Thank you very much.

**Comment by alanxz** [comment]
The current design of SimpleAmqpClient does not provide a way to set a timeout when publishing a message, nor is there a good way to add it to SimpleAmqpClient.  I'd recommend looking at rabbitmq-c which gives a bit more control when it comes to setting timeouts.
