### ISSUE TITLE
Network disconnect test: Connect times out after 64 seconds

### ISSUE THREAD

**Issue by kuroburki** [alanxz/SimpleAmqpClient#163]
Hi Allan,

I posted to the rabbitmq-c users group yesterday, but I am not able to update the post due to technical error with accessing google groups itself.  Below is a description of my problem and what I found so far:

1. I have updated SAC to enable heartbeats and set it to 10 secs.
2. My client uses SAC to make secure connection to RMQ.
3. While a connection is active/idle, I disconnect the network cable (disabled interface on VM)
4. Client detects this network disruption quickly thanks to heartbeats.
5. Client attempts a reconnect to the RabbitMQ server again.
6. The CreateSecure() blocks and returns after 64 secs.
7. Stack trace of the program shows poll() blocked. The timeout for poll was set to -1 (blocking call).

#0  0x00007ffff2a90dfd in poll () from /usr/lib64/libc.so.6
#1  0x00000000006aaff4 in amqp_poll (fd=15, event=4, deadline=...) at rabbitmq/amqp_socket.c:286
#2  0x00000000006ab381 in amqp_open_socket_inner (hostname=0x2085b98 "rabbit01", portnumber=5671, deadline=...) at rabbitmq/amqp_socket.c:501
#3  0x000000000069ff09 in amqp_ssl_socket_open (base=0x7fffe8011620, host=0x2085b98 "rabbit01", port=5671, timeout=0x0) at rabbitmq/amqp_openssl.c:192
#4  0x00000000006aadba in amqp_socket_open (self=0x7fffe8011620, host=0x2085b98 "rabbit01", port=5671) at rabbitmq/amqp_socket.c:225
#5  0x0000000000615a0f in AmqpClient::Channel::Channel (this=0x7fffe80116a0, host="rabbit01", port=5671, username="appuser", password="", vhost="/", frame_max=131072, ssl_params=...)
    at rabbitmq/Channel.cpp:176
#6  0x0000000000608380 in _ZN5boost11make_sharedIN10AmqpClient7ChannelERKSsIRiS4_S4_S4_S5_RNS2_19SSLConnectionParamsEEEENS_6detail15sp_if_not_arrayIT_E4typeEOT0_DpOT1_ (arg1="rabbit01")
    at /usr/include/boost/smart_ptr/make_shared_object.hpp:214
#7  0x0000000000606b44 in AmqpClient::Channel::CreateSecure (path_to_ca_cert="/rootca.cert.pem", host="rabbit01", path_to_client_key="", path_to_client_cert="", 
    port=5671, username="appuser", password="", vhost="/", frame_max=131072, verify_hostname=true) at ./include/SimpleAmqpClient/Channel.h:145
#8  0x000000000060512f in appmsg::AppMessager::reconnect (this=0x2085c30) at AppMessager.cpp:987

(gdb) f 1
#1  0x00000000006aaff4 in amqp_poll (fd=15, event=4, deadline=...) at rabbitmq/amqp_socket.c:286
286	  res = poll(&pfd, 1, timeout_ms);
(gdb) list
281	  timeout_ms = amqp_time_ms_until(deadline);
282	  if (-1 > timeout_ms) {
283	    return timeout_ms;
284	  }
285	
286	  res = poll(&pfd, 1, timeout_ms);
287	
288	  if (0 < res) {
289	    /* TODO: optimize this a bit by returning the AMQP_STATUS_SOCKET_ERROR or
290	     * equivalent when pdf.revent is POLLHUP or POLLERR, so an extra syscall
(gdb) p timeout_ms
$8 = -1
(gdb) 

Is there a way to modify this behavior and have the connect timeout sooner?

**Comment by kuroburki** [comment]
Additional information: The rabbitmq-c library was compiled with HAVE_POLL option.

**Comment by alanxz** [comment]
Answered on the [rabbitmq-c-users@googlegroups.com thread](https://groups.google.com/forum/#!msg/rabbitmq-c-users/K-50yat-OGg/vRuSD8YBBAAJ)
