### ISSUE TITLE
How to use amqp_basic_properties_t?

### ISSUE THREAD

**Issue by wolfelven** [alanxz/SimpleAmqpClient#184]
Hello, everyone.
I'm an newer for using amqp. Who can tell me how to use amqp_basic_properties_t_?
I'm want to set headers when using amqp publish.

**Comment by alanxz** [comment]
`amqp_basic_properties_t_` is a rabbitmq-c structure, and probably shouldn't be exposed in the SimpleAmqpClient interface. 

Instead create a BasicMessage object, and set properties on it using one of the accessor methods.
