### ISSUE TITLE
CMAKE Build issue on windows. 

### ISSUE THREAD

**Issue by chaithubk** [alanxz/SimpleAmqpClient#195]
I have downloaded the ZIP of the latest master source from GIT. And this is how I figured out to set the respective flags to build the source as per my need. 

```
C:\GIT\SimpleAmqpClient-master\build>cmake -DBOOST_ROOT="C:\GIT\boost_1_67_0" -DBOOST_LIBRARYDIR="C:\GIT\boost_1_67_0\stage\lib" -DBOOST_INCLUDEDIR="C:\GIT\boost_1_67_0\boost" -DRabbitmqc_INCLUDE_DIR="C:\GIT\rabbitmq-c-0.9.0\librabbitmq" -DRabbitmqc_LIBRARY="C:\GIT\rabbitmq-c-0.9.0\build\librabbitmq\Debug\rabbitmq.4.lib" -DBUILD_STATIC_LIBS=ON -DENABLE_SSL_SUPPORT=OFF -DBoost_USE_STATIC_LIBS=ON ..
-- Selecting Windows SDK version  to target Windows 10.0.16299.
-- Boost version: 1.67.0
-- Boost version: 1.67.0
-- Found the following Boost libraries:
--   chrono
--   system
-- Found Rabbitmqc
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
-- Configuring done
CMake Error at CMakeLists.txt:41 (add_executable):
  Cannot find source file:

    foo.cc

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at CMakeLists.txt:41 (add_executable):
  No SOURCES given to target: foo


-- Build files have been written to: C:/GIT/SimpleAmqpClient-master/build
```
I noticed an error that says "cannot find source file foo.cc" and due to that reason I guess I did not see the visual studio .sln file or any .lib and .dll files. 

So I have opened the CMakeLists.txt file and remove the below stuff: 
```
find_package(Boost 1.67.0)
if(Boost_FOUND)
  include_directories(${Boost_INCLUDE_DIRS})
  add_executable(foo foo.c)
endif()
```
After the above change, the build went fine and I am able to see the visual studio solution SimpleAmqpClient.sln in the build directory and I am able to build the source in Visual Studio. 

Am very new to this world, and I want to make sure the procedure I followed is correct and that I am contributing in a positive note to this project.

**Comment by alanxz** [comment]
Could you link to the lines in the CMakeLists.txt file in question?  I'm having trouble finding the lines you referenced in the code in this repository.

**Comment by chaithubk** [comment]
It's really surprising. I tried to unzip the same master branch which I used earlier when I reported this issue. Now I dont see any error with the foo.c and even I cant find the reference to those lines in the CMakeListst.txt in my source. I was trying multiple repos to learn about the AMQP client, and I dont know how I was able to see that issue. Really sorry, do you remember a state where you might have added a test example like foo.c ? 

But I feel like I cant make this up, because I have copied the output that I have seen in my PS as is in the post and now I cant reproduce it.

**Comment by alanxz** [comment]
Maybe the archive you got was from a fork of SimpleAmqpClient?
