### ISSUE TITLE
Unable to find the requested Boost libraries

### ISSUE THREAD

**Issue by ljhack** [alanxz/SimpleAmqpClient#212]
Hi alan,

Thanks for your great rabbitmq-c and SimpleAmqpClient projects.

I build boost and your rabbitmq-c from source. 

The one problem I encoutered when I build SimpleAmqpClient is that, after building I have to install boost and rabbitmq-c with root privilege.

$ pwd
/home/ljh/lib/SimpleAmqpClient-master/build
$ cmake ..
CMake Error at /usr/share/cmake/Modules/FindBoost.cmake:1138 (message):
  Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  CMakeLists.txt:41 (FIND_PACKAGE)

Rabbitmqc_INCLUDE_DIR=Rabbitmqc_INCLUDE_DIR-NOTFOUND
Rabbitmqc_LIBRARY=Rabbitmqc_LIBRARY-NOTFOUND
CMake Error at Modules/LibFindMacros.cmake:74 (message):
  Required library Rabbitmqc NOT FOUND.

  Install the library (dev version) and try again.  If the library is already
  installed, use ccmake to set the missing variables manually.
Call Stack (most recent call first):
  Modules/FindRabbitmqc.cmake:19 (LIBFIND_PROCESS)
  CMakeLists.txt:46 (FIND_PACKAGE)

-- Configuring incomplete, errors occurred!
See also "/home/ljh/lib/SimpleAmqpClient-master/build/CMakeFiles/CMakeOutput.log".
$

**Comment by mruki** [comment]
@linuxjh dunno if it is still an open question, but have you tried installing boost and rabbitmq somewhere, where you can and then provide the paths to cmake?
I was building this way successfully on windows:

```
# setting the environment variables
set BOOST_ROOT=%INSTALLATION_FOLDER%\boost.1.59.0
set BOOST_LIBRARYDIR=%INSTALLATION_FOLDER%\boost.1.59.0\lib\native\v100\Win32
# calling cmake
mkdir build64 && cd build64 && cmake -G "Visual Studio 10 2010 Win64" -DRabbitmqc_INCLUDE_DIR=%INSTALLATION_FOLDER%\rabbitmq-c-v100.0.7.1.0\include\librabbitmq -DRabbitmqc_LIBRARY=%INSTALLATION_FOLDER%\rabbitmq-c-v100.0.7.1.0\lib\native\static\Debug\x64\librabbitmq.4.lib ..
```

**Comment by linuxjh** [comment]
Thanks for help, mruki

Sent from my iPad

On Mar 8, 2019, at 22:39, mruki <notifications@github.com<mailto:notifications@github.com>> wrote:


@linuxjh<https://github.com/linuxjh> dunno if it is still an open question, but have you tried installing boost and rabbitmq somewhere, where you can and then provide the paths to cmake?
I was building this way successfully on windows:

# setting the environment variables
set BOOST_ROOT=%INSTALLATION_FOLDER%\boost.1.59.0
set BOOST_LIBRARYDIR=%INSTALLATION_FOLDER%\boost.1.59.0\lib\native\v100\Win32
# calling cmake
mkdir build64 && cd build64 && cmake -G "Visual Studio 10 2010 Win64" -DRabbitmqc_INCLUDE_DIR=%INSTALLATION_FOLDER%\rabbitmq-c-v100.0.7.1.0\include\librabbitmq -DRabbitmqc_LIBRARY=%INSTALLATION_FOLDER%\rabbitmq-c-v100.0.7.1.0\lib\native\static\Debug\x64\librabbitmq.4.lib ..
