### ISSUE TITLE
I am unable to send Headers along with the message; what am I doing wrong?

### ISSUE THREAD

**Issue by humayunkhan** [alanxz/SimpleAmqpClient#226]
Here is how my code looks like. I have a configuration object with some basic configuration values.

auto channel = AmqpClient::Channel::Create("localhost", 5672, configuration.UserName, configuration.Password, configuration.VirtualHost, 131072);

channel->DeclareQueue(configuration.QueueName, false, true, false, true);
auto messageBody = "simple json string message nothing fancy"
auto message = AmqpClient::BasicMessage::Create(messageBody);
message->DeliveryMode(AmqpClient::BasicMessage::delivery_mode_t::dm_nonpersistent);
message->ContentType("application/json");
message->Type("XYZRequest");
message->AppId("a guid");
auto headerTable = message->HeaderTable();
headersTable.insert(std::pair<string, string>("Key-1", "value-1"));
headersTable.insert(std::pair<string, string>("Key-2", "value-2"));

channel->BasicPublish(std::string(), configuration.ScoreQueueName, message);

This sends the message to the queue and I can see all the details on the RabbitMq management portal except the headers.

What am I missing? Is it some configuration or what is it?

I would appreciate if some one can give me a link to a basic tutorial on how to send headers.

I am stuck. Please help.

**Comment by alanxz** [comment]
Answered in https://stackoverflow.com/questions/58762955/rabbitmq-simpleamqpclient-i-am-trying-to-send-headers-along-with-my-message/58774736.

**Comment by humayunkhan** [comment]
Thanks.
