### ISSUE TITLE
WSO2 Message Broker support

### ISSUE THREAD

**Issue by chashikajw** [alanxz/SimpleAmqpClient#246]
I use this SimpleAMQPClient to subscribes to a topic in the wso2 message broker(https://docs.wso2.com/display/MB320/About+WSO2+Message+Broker). It's compliant with amqp0-9. But when I am going declare a queue or an exchange it returns the following error

That message broker support JMS. I need to find a c++ subscriber which support with the broker.

Is there a way to fix this issue on the client-side. or it should handle from the broker side? 

![image](https://user-images.githubusercontent.com/21282060/87598673-df6ba780-c710-11ea-8d1e-3599f3aec1f4.png)

**Comment by alanxz** [comment]
SimpleAmqpClient uses a RabbitMQ extension called [publisher confirms](https://www.rabbitmq.com/confirms.html).

In this case WSO2 doesn't support this extension. Unfortunately this means that SimpleAmqpClient cannot be used with WSO2, as it relies on this extension.

https://github.com/alanxz/rabbitmq-c might work as use of this extension is optional.

**Comment by chashikajw** [comment]
Okay. Thanks for the information.
