### ISSUE TITLE
Debian build stopped working after July 21st 2020

### ISSUE THREAD

**Issue by winfij** [alanxz/SimpleAmqpClient#265]
Up until recently we were able to checkout the code on Debian and just run cmake/make to build.
However in commit 47f4c79bb8570c5f7d4c5c560f2ba4f208aaf212 which was nominally for "API docs polishing" in the CMakeLists.txt file there was an additional change removing the line:

`include(GNUInstallDirs)`

which means the default install dirs are no longer defined.
Given the doxygen changes just before that line and the lack of any mention in the commit, I'm assuming the deletion of that line was accidental.

Indeed, if I reinstate that line, the simple cmake on Debian starts working for us again.

Would it be possible to get that line reinstated in the repo, or the build instructions updated?

**Comment by alanxz** [comment]
Good catch, #267 is out to fix this.
