### ISSUE TITLE
Why I get AmqpLibraryException？

### ISSUE THREAD

**Issue by lv254165754** [alanxz/SimpleAmqpClient#274]
**I want to catch ConnectionException，
so I closed My RabbitMQ broker(version 3.8.5)。**
[SimpleAmqpClien version 2.5.1]
[rabbitmq-c 0.10.0]

```
try
	{
		Channel = AmqpClient::Channel::Create("localhost");
		Channel->DeclareExchange("Test", "topic", false, true, false);
	}
	catch (AmqpClient::ConnectionException &e)
	{
		
		std::cout << e.what();
		return -1;
	}
```

**but it throw “AmqpLibraryException” exception(means errors arising from incorrect usage of this library APIs????  ) , I can not catch this exception .**

**I think it should throw ConnectionException or ConnectionClosed Exception instead of AmqpLibraryException.**

**Comment by lv254165754** [comment]
![image](https://user-images.githubusercontent.com/64194454/92568933-78064a00-f2b2-11ea-90b6-6975db8f6f10.png)

And e.what() means the program knows it is **"a socket error occurred"**

but the The type of exception is **AmqpLibraryException**


Is that reasonable?

**Comment by alanxz** [comment]
The documentation for `AmqpLibraryException` is a bit misleading, this is something that can be thrown if an error occurs with the underlying socket (e.g., if the connection unexpectedly drops).

I agree with you that `AmqpLibraryException` is a bit inconsistent with what should be thrown, and that something like `ConnectionClosedException` might be a better exception to throw in this case.
