### ISSUE TITLE
vcpkg support?

### ISSUE THREAD

**Issue by jdx-john** [alanxz/SimpleAmqpClient#298]
I don't know much about ampq/Rabbit but we have a dependency on SimpleAmpqClient in our software. We are trying to migrate to vcpkg and when I look there I see some projects listed already:

```
C:\github\microsoft\vcpkg>vcpkg search amqp
amqpcpp              4.3.11           AMQP-CPP is a C++ library for communicating with a RabbitMQ message broker
azure-uamqp-c        2020-12-09       AMQP library for C
azure-uamqp-c[public-preview]         AMQP library for C (public preview)
librabbitmq          2020-06-03       A C-language AMQP client library for use with v2.0+ of the RabbitMQ broker.
```

Can I check firstly, that none of these _is_ your project? If not, would you consider it? As a CMake-based build it looks like this would be a good fit.

**Comment by alanxz** [comment]
I can confirm that none of those are SimpleAmqpClient.  

librabbitmq appears to be the library that SimpleAmqpClient depends on (rabbitmq-c).
