### ISSUE TITLE
Version 2.4 compatibility with newer Rabbit servers

### ISSUE THREAD

**Issue by gitzko** [alanxz/SimpleAmqpClient#321]
Hi, can anyone share their experiences with library v2.4 usage with newer RabbitMQ server versions like 3.10 or 3.11?
Is there a client server compatiblity matrix somewhere?
If I have to build this library to use newer Rabbit, how much library API has changed between v2.4 and v2.5.1, will it work with Boost 1.55?

**Comment by alanxz** [comment]
SimpleAmqpClient should work with current modern RabbitMQ broker (SimpleAmqpClient communicates with the RabbitMQ flavor of AMQP v0.9.1 the).

It should also work with modern boost versions as well.

**Comment by gitzko** [comment]
Thanks, but we have a build of version 2.4, will that one work with the newer RabbitMQ?

**Comment by alanxz** [comment]
I believe it should also work.

**Comment by gitzko** [comment]
Thanks!
