### ISSUE TITLE
Keep alive for long running connections

### ISSUE THREAD

**Issue by gitzko** [alanxz/SimpleAmqpClient#324]
Does this lib support tcp keep alive of some sort? Docker Swarm seems to be closing NAT connection after 4 minutes.

**Comment by alanxz** [comment]
rabbitmq-c (which wraps SimpleAmqpClient) enables TCP keepalive by default.  It uses whatever the system's default keepalive interval is.

**Comment by gitzko** [comment]
But it doesn't seem to stop the HAProxy from dropping the client connection.

**Comment by alanxz** [comment]
The default interval for TCP keepalives is quite long (2h).  As an experiment try setting the keepalive interval on your system to something shorter than the 4-minutes that HAProxy is using to terminate your connection.
