### ISSUE TITLE
On the issue of creating channels

### ISSUE THREAD

**Issue by bbj767475974** [alanxz/SimpleAmqpClient#332]
Hello, may I ask why creating a channel using Create failed with a local IP address? Localhost can be created, and the following figure shows the error reported.

**Comment by bbj767475974** [comment]
[
![Uploading 2e7064cca57202fc86890f8209be030.jpg…]()
](url)

**Comment by bbj767475974** [comment]
![2e7064cca57202fc86890f8209be030](https://github.com/alanxz/SimpleAmqpClient/assets/61446077/02f38154-e15a-4a06-93fb-86ac63c1286b)
l'lll

**Comment by alanxz** [comment]
AccessRefusedException means that the client hasn't correctly authenticated with the broker. Check to make sure you're supplying the correct username/password.

**Comment by bbj767475974** [comment]
I only filled in the local IP address and also reported this error, such as 188.100.1.85. The IP address has been configured on my computer

**Comment by alanxz** [comment]
The RabbitMQ broker allows configuration of auth based on which IP it listens on, its possible that the user is only configured on one host.  Check the broker logs for details on the login failures.

**Comment by bbj767475974** [comment]
Hello, I have checked and modified the log file regarding the above issue. The main reason is the issue with creating users. What should I do if I want to use the local IP address as the server address? I have currently modified the config file, which is normal after restarting the service, but I cannot access it through a browser. Why is this？

**Comment by bbj767475974** [comment]
![Uploading f5ebe48b8739e9cec1d2e9b2dc65417.jpg…]()

**Comment by bbj767475974** [comment]
![Uploading f5ebe48b8739e9cec1d2e9b2dc65417.jpg…]()
l

**Comment by bbj767475974** [comment]
![Uploading f5ebe48b8739e9cec1d2e9b2dc65417.jpg…]()
ll

**Comment by bbj767475974** [comment]
![f5ebe48b8739e9cec1d2e9b2dc65417](https://github.com/alanxz/SimpleAmqpClient/assets/61446077/95ad3c43-7a99-4781-897b-c2ced8ab1848)
