### ISSUE TITLE
build error with boost 1.53

### ISSUE THREAD

**Issue by bburas** [alanxz/SimpleAmqpClient#345]
Trying to build from source on redhat 7.9, boost 1.53, g++ 12.1.1
$ make
Consolidate compiler generated dependencies of target SimpleAmqpClient
[ 9%] Building CXX object CMakeFiles/SimpleAmqpClient.dir/src/BasicMessage.cpp.o
/home/bburas/projects/broker-demo/SimpleAmqpClient/src/BasicMessage.cpp: In member function 'const string& AmqpClient::BasicMessage::ContentType() const':
/home/bburas/projects/broker-demo/SimpleAmqpClient/src/BasicMessage.cpp:77:33: error: 'class boost::optional<std::basic_string >' has no member named 'value'
77 | return m_impl->content_type.value();

**Comment by alanxz** [comment]
Looks like boost::optional::value isn't a part of the API in v1.53. I've added #346, see if this fixes the issue you were having.
