### ISSUE TITLE
Listening to messages with given routing key

### ISSUE THREAD

**Issue by adambadura** [alanxz/SimpleAmqpClient#45]
I need code that would connect to RabbitMQ with specified connection data and exchange. Then it would create a temporary (for program lifetime only) queue and listen for messages with specified routing key. This is what [alanxz/rabbitmq-c](https://github.com/alanxz/rabbitmq-c) does in [examples/amqp_listen.c](https://github.com/alanxz/rabbitmq-c/blob/master/examples/amqp_listen.c).

How to achieve that with this library? I wasn't able to do it myself and none of the examples seems to illustrate this.

When I just run the code similar to the one given in [README.md](https://github.com/alanxz/SimpleAmqpClient/blob/master/README.md) (by which I mean `AmqpClient::Channel::Create`, `DeclareQueue`, `BasicConsume`, `BasicConsumeMessage`) it never exits `BasicConsumeMessage` even after publishing messages (using RabbitMQ Management web page, which claims the message has been routed).

Since the above procedure does not use at any point routing key I tried adding `BindQueue` between `DeclareQueue` and `BasicConsume` with my routing key. After that change `BasicConsumeMessage` fails with `bad_alloc` (in `SimpleAmqpClient` code) after I publish a message.

**Comment by swatinair123** [comment]
Hi I am running my code in win 32 debug mode. But I am writing a simple code for sending the msg. But my code crashes at  channel->BindQueue(queue, exchange, routing_key);
with the exception Microsoft C++ exception: [rethrow] at memory location 0x00000000.
icrosoft C++ exception: AmqpClient::AccessRefusedException at memory location 0x008FF080. .
Can anyone pls help?
