### ISSUE TITLE
Build SimpleAmqpClient with Microsoft Studio 2012, window 7 32 bit

### ISSUE THREAD

**Issue by simonqiang** [alanxz/SimpleAmqpClient#80]
I need to compile SimpleAmqpClient on my Window 7 32bit machine. 

What I have done is : 
1. cmake rabbitmq-c  by using below commands 
              --    mkdir build && cd build
              --    cmake .. -DENABLE_SSL_SUPPORT=OFF -DDBUILD_STATIC_LIBS=ON
2. open rabbitmq-c.sln file with MS 2012 and build
3. cmake SimpleAmqpClient by using below commands 
              --    mkdir SimpleAmqpClient-build && cd SimpleAmqpClient-build
              --    cmake -DBOOST_ROOT="F:\SourceCode\boost\1.5.5\boost_1_55_0" -DBOOST_LIBRARYDIR="F:\SourceCode\boost\1.5.5\boost_1_55_0\stage\lib" -DBOOST_INCLUDEDIR="F:\SourceCode\boost\1.5.5\boost_1_55_0" -DRabbitmqc_INCLUDE_DIR="F:\SourceCode\Rabbit\rabbitmq-c\librabbitmq" -DRabbitmqc_LIBRARY="F:\SourceCode\Rabbit\rabbitmq-c-master\build\librabbitmq\Debug\rabbitmq.1.lib" -DBUILD_STATIC_LIBS=ON -DENABLE_SSL_SUPPORT=OFF -DBoost_USE_STATIC_LIBS=ON -DDOXYFILE_LATEX=OFF "../SimpleAmqpClient"
4. open SimpleAmqpClient.sln file with MS 2012 and build
   Error appear when I try to the solution. below are the error messages. 

2>  Generating Code...
2>     Creating library F:/SourceCode/Rabbit/simpleamqpclient-build/Debug/SimpleAmqpClient.2.lib and object F:/SourceCode/Rabbit/simpleamqpclient-build/Debug/SimpleAmqpClient.2.exp
2>Channel.obj : error LNK2019: unresolved external symbol _amqp_ssl_socket_new referenced in function __catch$??0Channel@AmqpClient@@QAE@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H000H@Z$0
2>Channel.obj : error LNK2019: unresolved external symbol _amqp_ssl_socket_set_cacert referenced in function __catch$??0Channel@AmqpClient@@QAE@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H000H@Z$0
2>Channel.obj : error LNK2019: unresolved external symbol _amqp_ssl_socket_set_key referenced in function __catch$??0Channel@AmqpClient@@QAE@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H000H@Z$0
2>F:\SourceCode\Rabbit\simpleamqpclient-build\Debug\SimpleAmqpClient.2.dll : fatal error LNK1120: 3 unresolved externals 

anyone know how to resolve this error ? thanks in advance !

**Comment by vikaschamp** [comment]
Hello  Friends ,

How can i declare queue , exchnage and publish a message .

I have wrote code but its not working . It's creating channel but not creating queue exchange...


#include "stdafx.h"

#include <SimpleAmqpClient/SimpleAmqpClient.h>


int main()
{
	AmqpClient::Channel::ptr_t connection = AmqpClient::Channel::Create("localhost" ,5672 ,"finsoltech" , "pass123!" , "/");
	connection->DeclareQueue("myQueue", false, false, true, true);
	connection->DeclareExchange("myExchnage");


    return 0;
}


Please suggest me where am i doing wrong.
Thanks in advance.

**Comment by swatinair123** [comment]
Hi is there an option without SSL support as of now?
