### ISSUE TITLE
help in debugging error SimpleSubscriber.cpp

### ISSUE THREAD

**Issue by legend1910** [alanxz/SimpleAmqpClient#92]
Hi, 
i am new to this i just tried to create a consumer program which reads from multiple queues .I am using QT in UBUNTU  so when i went through the Google i cam across this example. when i tried to run the SimpleSubscriber.cpp alone and included the SimpleAmqpClient in the directory  and added the headers too. When i build i get an error in my QT can u guys suggest what this error why it has occurred and help me out to solve it .

This is the error i get while building my project 

error: could not convert 'AmqpClient::Channel::BasicConsumeMessage()()' from 'AmqpClient::Envelope::ptr_t {aka boost::shared_ptrAmqpClient::Envelope}' to 'AmqpClient::BasicMessage::ptr_t {aka boost::shared_ptrAmqpClient::BasicMessage}'
        return m_channel->BasicConsumeMessage();
                                              ^

**Comment by kmgalanakis** [comment]
Hi! On SimpleSubscriber.h I get a 

> error C2063: 'boost::make_shared' : not a function	c:\vs2013 projects\rabbitmqtutorialv2\rabbitmqtutorialv2\simplesubscriber.h	54	1	RabbitMQTutorialV2

```
friend ptr_t boost::make_shared<SimpleSubscriber>(AmqpClient::Channel::ptr_t const &a1, std::string const &a2);
```

Can you help me please?

**Comment by alanxz** [comment]
See comment above, they were written for an earlier version of the library.
